# frozen_string_literal: true

# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubystyle-guide.org/
class Devforge < Formula
  desc "DevForge — Design intelligence (CLI/TUI + MCP server) + image/video/audio processing (dpf)"
  homepage "https://github.com/GustavoGutierrez/devforge-mcp"
  license "GPL-3.0"

  # Bottle URLs are populated by the release workflow.
  # If no bottle is available, Homebrew falls back to building from source.

  url "https://github.com/GustavoGutierrez/devforge-mcp/archive/refs/tags/v#{version}.tar.gz"
  version "#{version}"
  sha256 "use_homebrew_autogenerated_value"

  # Pre-built bottles are downloaded from GitHub Releases.
  # No source build needed — keeps install fast and avoids CGO complexity.

  # dpf (DevPixelForge) uses ffmpeg for video/audio operations
  depends_on "ffmpeg" if OS.mac?

  # Bottles are built by the release workflow:
  #   - macOS: ARM64 (Apple Silicon) + x86_64 (Intel)
  #   - Linux:  x86_64 (Ubuntu/Debian/Fedora)
  if OS.mac?
    on_macos_sequential do
      url "https://github.com/GustavoGutierrez/devforge-mcp/releases/download/v#{version}/devforge-#{version}.macos-intel.tar.gz"
      sha256 "use_homebrew_autogenerated_value"
    end
    on_macos_apple do
      url "https://github.com/GustavoGutierrez/devforge-mcp/releases/download/v#{version}/devforge-#{version}.macos-arm64.tar.gz"
      sha256 "use_homebrew_autogenerated_value"
    end
  end

  if OS.linux?
    on_linux do
      url "https://github.com/GustavoGutierrez/devforge-mcp/releases/download/v#{version}/devforge-#{version}.linux-amd64.tar.gz"
      sha256 "use_homebrew_autogenerated_value"
    end
  end

  def install
    # Install pre-built binaries from our release assets.
    # This is much faster than building from source and avoids CGO complexity.

    if OS.mac?
      # macOS: download the macOS tarball (contains devforge, devforge-mcp, dpf)
      system "curl", "-sSL", "--fail",
             "-o", "brew-bottle.tar.gz",
             "https://github.com/GustavoGutierrez/devforge-mcp/releases/download/v#{version}/devforge-#{version}.macos-#{Hardware::CPU.intel? ? "intel" : "arm64"}.tar.gz"
      system "tar", "-xzf", "brew-bottle.tar.gz"
      FileUtils.rm_f "brew-bottle.tar.gz"
      libexec.install "devforge-mcp", "devforge", "dpf"

    elsif OS.linux?
      # Linux: download the Linux tarball (contains devforge, devforge-mcp, dpf)
      system "curl", "-sSL", "--fail",
             "-o", "brew-bottle.tar.gz",
             "https://github.com/GustavoGutierrez/devforge-mcp/releases/download/v#{version}/devforge-#{version}.linux-amd64.tar.gz"
      system "tar", "-xzf", "brew-bottle.tar.gz"
      FileUtils.rm_f "brew-bottle.tar.gz"
      libexec.install "devforge-mcp", "devforge", "dpf"
    end

    # Create shell wrappers in bin/. These are real executables (not symlinks)
    # so that os.Executable() in the Go code resolves to the libexec path,
    # allowing dpf and the database to be found next to the binary.
    File.write(bin/"devforge-mcp", <<~WRAPPER)
      #!/bin/sh
      # This file is generated by the Homebrew formula.
      # DO NOT EDIT — instead edit the formula and re-run brew install.
      exec "#{libexec}/devforge-mcp" "$@"
    WRAPPER
    FileUtils.chmod 0755, bin/"devforge-mcp"

    File.write(bin/"devforge", <<~WRAPPER)
      #!/bin/sh
      # This file is generated by the Homebrew formula.
      # DO NOT EDIT — instead edit the formula and re-run brew install.
      exec "#{libexec}/devforge" "$@"
    WRAPPER
    FileUtils.chmod 0755, bin/"devforge"
  end

  def post_install
    # Ensure the config directory exists and create a default config if missing.
    # The Go code reads from ~/.config/devforge/config.json.
    config_dir = Dir.home.join(".config", "devforge")
    config_file = config_dir.join("config.json")

    return if config_file.exist?

    config_dir.mkpath
    config_file.write default_config_json
    config_file.chmod 0o600
  end

  def caveats
    <<~EOS
      DevForge installed! Three components are available:

        devforge       — CLI/TUI design system manager (Bubble Tea)
        devforge-mcp   — MCP server (stdio transport) for AI IDEs
        dpf            — DevPixelForge: multimedia processing engine (Rust)

      Config file: ~/.config/devforge/config.json

      ── CLI/TUI ──────────────────────────────────────────────────────────────

        devforge

      ── MCP Server Setup (AI IDE integration) ───────────────────────────────

      Add to your AI client's MCP configuration:

        {
          "mcpServers": {
            "devforge": {
              "command": "#{opt_bin}/devforge-mcp",
              "env": {}
            }
          }
        }

      Config file locations:
        OpenCode    →  ~/.config/opencode/config.json
        Claude      →  ~/.config/claude-desktop.json
        VS Code     →  ~/Library/Application Support/Code/User/settings.json
        Cursor      →  ~/.config/cursor/settings.json

      ── Optional: Gemini API Key ─────────────────────────────────────────────

        devforge config set gemini_api_key YOUR_KEY

      Or edit ~/.config/devforge/config.json directly.

      ── Updating ─────────────────────────────────────────────────────────────

        brew upgrade devforge

      ── Linux (Ubuntu/Debian) ───────────────────────────────────────────────

      On Linux, install FFmpeg separately:

        # Ubuntu/Debian
        sudo apt install ffmpeg

        # Fedora
        sudo dnf install ffmpeg
    EOS
  end

  # ── Helpers ────────────────────────────────────────────────────────────────────

  # The dpf version is pinned to a known compatible release.
  # Update this when DevPixelForge releases a new version.
  def dpf_version
    "0.2.0"
  end

  def default_config_json
    <<~JSON
      {
        "gemini_api_key": "",
        "ollama_url": "http://localhost:11434",
        "embedding_model": "nomic-embed-text",
        "image_model": "gemini-2.5-flash-image"
      }
    JSON
  end

  test do
    # Verify both binaries exist and are executable
    assert_predicate bin/"devforge-mcp", :executable?, "devforge-mcp not executable"
    assert_predicate bin/"devforge", :executable?, "devforge not executable"

    # Verify devforge-mcp responds (stdio tool — just check it doesn't crash)
    # We can't fully test MCP protocol without a client, but we can verify
    # the binary runs and exits cleanly.
    assert_match "", shell_output("#{bin}/devforge-mcp 2>&1", 1)
  rescue Errno::ENOENT => e
    # Binary not built yet — this happens during `brew test`
    skip "Binary not yet built: #{e.message}"
  end
end
